name: Build and Test - Classroom

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install common packages
      - name: Install dependencies
        run: |
          sudo apt update

          sudo apt install -y build-essential default-jdk nasm gdb vim \
                              python3-pip ninja-build libglib2.0-dev libpixman-1-dev meson \
                              curl git htop jq locales sudo tzdata wget
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y gcc-multilib libc6:i386 libc6-dev-i386
          sudo apt install -y gcc-riscv64-unknown-elf gcc-riscv64-linux-gnu qemu-user
          pip install tomli

      # Step 3: Verify installations
      - name: Verify toolchain
        run: |
          gcc --version
          gcc -m32 --version
          nasm -v
          qemu-riscv64 --version || true
          riscv64-unknown-elf-gcc --version || true
          riscv64-linux-gnu-gcc --version || true

      # Step 4: Build project
      - name: Build project
        run: make

      - name: Make .pipe files
        run: |
          echo "Creating named pipes..."
          mkfifo server.pipe
          mkfifo anthony.pipe
          mkfifo bob.pipe
          mkfifo person1.pipe
          mkfifo person2.pipe

      - name: Run autograder
        run: bash run_test.sh

      # echo "Starting server..."
      # ./server &
      # SERVER_PID=$!

      # sleep 1 

      # echo "Running client via QEMU..."
      # qemu-riscv64 ./client 

      # echo "Waiting for server to finish..."
      # wait $SERVER_PID
